### ISSUE TITLE
Issue with file denver/graphics3d.py TypeError

### ISSUE THREAD

**Issue by xcodz-dot** [xcodz-dot/denver#13]
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1\plugins\python-ce\helpers\pycharm\docrunner.py", line 330, in <module>
    module = loadSource(a[0])
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1\plugins\python-ce\helpers\pycharm\docrunner.py", line 237, in loadSource
    module = _load_file(moduleName, fileName)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1\plugins\python-ce\helpers\pycharm\docrunner.py", line 209, in _load_file
    return machinery.SourceFileLoader(moduleName, fileName).load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:/Xcodz/denver/denver/graphics3d.py", line 13, in <module>
    ModelType = NewType("ModelType", list[tuple[tuple[int]]])
TypeError: 'type' object is not subscriptable

Process finished with exit code 1
```
<img width="960" alt="Issue_Denver_graphics3d-1" src="https://user-images.githubusercontent.com/71920621/94362594-27785480-00da-11eb-99a4-202519caa6f3.png">

**Comment by xcodz-dot** [comment]
please fix this

**Comment by xcodz-dot** [comment]
i will be removing some lines from this file, if no one comes with a solution.

**Comment by xcodz-dot** [comment]
fixed
